In [ ]:
# import kagglehub

# # Download latest version
# path = kagglehub.dataset_download("anshumish/crop-yield-data-with-soil-and-weather-dataset")

# print("Path to dataset files:", path)

c:\Users\chandru.sivakumar\AppData\Local\Programs\Python\Python314\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Path to dataset files: C:\Users\chandru.sivakumar\.cache\kagglehub\datasets\anshumish\crop-yield-data-with-soil-and-weather-dataset\versions\1

In [ ]:
# import shutil
# import os


# os.listdir(path)
# for file_name in os.listdir(path):
#     source = os.path.join(path, file_name)
#     destination = os.path.join(os.getcwd(), file_name)

#     if os.path.isfile(source):
#         shutil.move(source, destination)

In [1]:
import pandas as pd

In [3]:
df_yield = pd.read_csv(r"d:\CropAdvisory\dataAnalysis\data\crop_yield.csv")
df_soil = pd.read_csv(r"d:\CropAdvisory\dataAnalysis\data\state_soil_data.csv")
df_weather = pd.read_csv(r"d:\CropAdvisory\dataAnalysis\data\state_weather_data_1997_2020.csv")

In [4]:
df_yield.head()

,crop,year,season,state,area,production,fertilizer,pesticide,yield
0,Arecanut,1997,Whole Year,Assam,73814.0,56708,7024878.38,22882.34,0.796087
1,Arhar/Tur,1997,Kharif,Assam,6637.0,4685,631643.29,2057.47,0.710435
2,Castor seed,1997,Kharif,Assam,796.0,22,75755.32,246.76,0.238333
3,Coconut,1997,Whole Year,Assam,19656.0,126905000,1870661.52,6093.36,5238.051739
4,Cotton(lint),1997,Kharif,Assam,1739.0,794,165500.63,539.09,0.420909

In [5]:
df_soil.head()

               state   N   P   K   pH
0     Andhra Pradesh  78  45  22  6.8
1  Arunachal Pradesh  55  15  35  5.5
2              Assam  60  18  38  5.8
3              Bihar  85  30  25  7.2
4       Chhattisgarh  70  35  20  6.5

In [6]:
df_weather.head()

            state  year  avg_temp_c  total_rainfall_mm  avg_humidity_percent
0  Andhra Pradesh  1997       28.21            1191.08                 69.56
1  Andhra Pradesh  1998       28.21            1100.41                 71.95
2  Andhra Pradesh  1999       28.03             603.67                 66.91
3  Andhra Pradesh  2000       27.74            1070.25                 70.73
4  Andhra Pradesh  2001       28.08             910.13                 68.69